# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M3gs5zxehuDv7moPK06dYLZTyb-vFws5
"""

def multiply_list(numbers):
  tot=1
  for x in numbers:
    tot *= x
  return tot
print(multiply_list([2,3,6]))

def last(n): return n[-1]
def sort_list_last(tuples):
  return sorted(tuples, key=last)
Sample_List=[(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]
print(sort_list_last(Sample_List))

from collections import Counter
d1 = {'a':100, 'b':200, 'c':300}
d2 = {'a':300, 'b':200, 'd':400}

d = Counter(d1) + Counter(d2)
print(d)

number = int(input("Type a number: "))

numberDict = {}
for i in range(1, number+1):
  numberDict[i] = i*i

print(numberDirect)

price = [('item1','12.20'), ('item2', '15.10'), ('item3','24.5')]
print( sorted(price, key=lambda x: float(x[1]), reverse=True))