# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DFrWwOOwxm36TnWVvY7fTnD3bMyCtUfH
"""

def maximum(a,b,c):
  list = [a,b,c]
  return max(list)

x= int(input("Enter First number"))
y= int(input("Enter Second number"))
z= int(input("Enter Therd number "))
print("Maximum Number is ::>", maximum(x, y, z))

def func(a,b) :
  sum_ = a+b
  sub_ = a-b
  return sum_,sub_

def sum(a,b):
  return a+b

def wer(a,b):
  return a*b


list =[11, 12, 5, 5, 56]
liste1=[]
liste2=[]
for ele in range(len(list)):
   if ele %2==0:
     liste1.append(list[ele])
   else:
      liste2.append(list[ele])
  
res1=0 
for i in liste1:
  res1=sum(res1,i)
print(res1)

res2=1
for i in liste2:
  res2=wer(res2,i)
print(res2)

n= input("enter the string: ")
l=n.split('-')
l.sort()
print('-'.join(l))