# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mNPCcVcjJAoDEGYlNPiOCq8VxnhRagay
"""

print("Welcome to python world! Let's start coding")