# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k9VZWpDO7TxDmEoDXULzMA0zqdSKpDh_
"""

fname = input("Input your  First name :Robert")
lname = input("Input  your last name :Loubart")
print = ("Hello Loubart Robert")

a=input()
n1= int(a)
n2= int(a+a)
n3= int(a+a+a)
print(n1+n2+n3)

num = int(input("Enter a number : "))
mod = num
if mod > 0 :
  print("This is an odd number")
else:
  print("This is an even number")

n1=[]
for x in range(2000, 3200):
  if (x%7==0) and (x%5==0):
    n1.append (str(x))
print(','.join(n1))



def odd_values_strings(str):
  result = ""
  for i in range (len(str)):
    if i % 2 == 0: 
      result = result + str[i]
  return result

print( odd_values_string('hello team'))
print( odd_values_string('hlota'))

price= int(input("Enter the price of your item:" ))
if price >= 500:
   price= price-(price * 0.5 ) 
   print(price)
elif price in range (200, 500):
   price= price-(price * 0.3)
   print(price)
elif price < 200:
   price= price-(price * 0.1)
   print(price)