# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18fpVPlcZMgPlQmVlTQVv81sCPTHZGCX7
"""

def file_read(fname):
        txt = open("python.txt")
        print(txt.read())

file_read('test.txt')

def file_read_from_head(fname, nlines):
        from itertools import islice
        with open("python.txt") as f:
                for line in islice(f, nlines):
                        print(line)
file_read_from_head('test.txt',2)

def LastNlines (fname, N):
  with open("python.txt") as file:
    for line in (file.readlines() [-N: ]):
      print(line, end ='')

def count_words(filepath):
  with open(filepath) as f:
    data = f.read()
    data.replace(",", " ")
    return len(data.split(" "))
print(count_words("python.txt"))