# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r4pTUjl5n8aj-HlYllOiksvuKEhM4Z7N
"""

mylist=[14, "hello", 967]
mylist=[6]

import pandas as pd
import numpy as np

print("python errors")

mydictionnary={True:"hello",False:"bye", '3':"python"}
mydictionnary=['True']

i=14
while i<78:
print(i)
i=i+1

it=iter([1,2,3])
next(it)
next(it)
next(it)

15+15

print('python')

def

x=19/5