# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S38qpbmZIKqBSTvbPZfZQ0T970CLnqoI
"""

import pandas as pd
import numpy as np

exam_data = {'name': ['Anastasia', 'Dina', 'Katherine', 'James',  'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
                       'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
                       'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
                       'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print(df)

df.head(3)

df = df.dropna()

print(df)

import pandas as pd
import numpy as np

exam_data = {'name': ['Anastasia', 'Dina', 'Katherine', 'James',  'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
                       'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
                       'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
                       'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)

print(df)

df[['name','score']].tail

import pandas as pd
import numpy as np

exam_data = {'name': ['Anastasia', 'Dina', 'Katherine', 'James',  'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
                       'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
                       'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
                       'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("Original rox=ws:")
print(df)
print("\Append a nex row:")
df.loc['k'] = [1, 'Surech','yes',15.5]
print("Print all records after insert a new record:")
print(df)
print("\nDelete the new row and display the original rows:")
df = df.drop('k')
print(df)

import pandas as pd
import numpy as np

exam_data = {'name': ['Anastasia', 'Dina', 'Katherine', 'James',  'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
                       'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
                       'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
                       'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print(df)
print("\nDelete the 'attempts column from the data frame:")
df.pop('attempts')
print(df)

import pandas as pd
import numpy as np


exam_data = {'name': ['Anastasia', 'Dina', 'Katherine', 'James',  'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
                       'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
                       'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
                       'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)

df['success']= np.where(df['score'] >10,1,0)
df

import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dina', 'Katherine', 'James',  'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
                       'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
                       'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
                       'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
df.to_csv()